config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :visits

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'
  get 'about', to: 'landings#about'
  get 'info', to: 'landings#info'
  get 'rent', to: 'landings#rent'
  get 'terms', to: 'landings#terms'
  get 'ready', to: 'landings#ready'
  get 'issue', to: 'landings#issue'
  post 'issue', to: 'landings#submit'
  get 'exit', to: 'visits#exit'
  get 'end', to: 'visits#end'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/models/pod.rb
class Pod < ActiveRecord::Base
  has_many :visits
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  has_many :visits
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :user
  belongs_to :pod
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end

  def about
  	@about = "This works the way it should"
  end

  def info
  	@info = "YAYAYAYAYAY!!!!"
  end

  def issue

  end

  def submit
    issue = Issue.new
    issue.email = params[:issue][:email]
    issue.message = params[:issue][:message]

    if issue.save
      redirect_to action: "index"
    else
      redirect_to action: "issue"
    end
  end

  def rent
    @visit = Visit.new
  end

  def terms

  end

  def ready

  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper
  protect_from_forgery with: :null_session

  def create
    puts params[:stripeToken]
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  protect_from_forgery with: :null_session

  # before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  # before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @code = Visit.find(params[:id]).pod.door_code
  end

  def exit

  end

  def end
    visit = Visit.find(params[:end][:id])


    begin_time = visit.created_at
    end_time = Time.now
    total_time = end_time - begin_time
    minutes = total_time/60
    hours = minutes/60
    @hours = (minutes/60).to_i
    @minutes = (minutes%60).round
    if @minutes < 10
      @minutes = sprintf '%02d', @minutes
    end

    @amount = (hours*2)*10

    if minutes%30 > 5
      @amount+=10
    end

    cents = (@amount*100)

    unless cents = 0
      Stripe::Charge.create(
          :amount => cents, # incents
          :currency => "usd",
          :customer => visit.customer_id
      )
      visit.destroy
    end

  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)
    pod = Pod.create(door_code: 1234)
    @visit.pod_id = pod.id

      # Amount in cents
      @amount = 500
      puts params[:stripeToken]

      customer = Stripe::Customer.create(
        :email => params[:email][0],
        :card  => params[:stripeToken]
      )

      @visit.customer_id = customer.id

      # charge = Stripe::Charge.create(
      #   :customer    => customer.id,
      #   :amount      => @amount,
      #   :description => 'Rails Stripe customer',
      #   :currency    => 'usd'
      # )

    # rescue Stripe::CardError => e
    #   flash[:error] = e.message
    #   redirect_to charges_path
    # end

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Enjoy your quiet time.' }
      else
        # format.html { render :new }
        # format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      # params.require(:visit).permit(:user_id, :pod_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class Float
	  def round_down n=0
	  s = self.to_s
	  l = s.index('.') + 1 + n
	  s.length <= l ? self : s[0,l].to_f
	  end
	end
end

app/helpers/floats.rb
class Float
  def round_down n=0
  s = self.to_s
  l = s.index('.') + 1 + n
  s.length <= l ? self : s[0,l].to_f
  end
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/elements/_header.html.erb
<header class="center">
  <h1 class="header">IsoPods</h1>
</header>

app/views/landings/about.html.erb
<div class="row">
	<ul class="info">
		<li class="list">IsoPods are an escape from the stresses and
mayhem of traveling.</li>
		<li class="list">Each pod is soundproofed to provide a quiet
and comfortable environment allowing
relaxation.</li>
		<li class="list">Each Pod provides access to wireless
internet, power for charging devices, a TV for
watching movies or TV shows from devices,
and a fold down desk.</li>
		<li class="list">Each pod also contains a comfortable
reclining chair and a fold down foot stool for
maximum comfort.</li>
		<li class="list">IsoPods are rented on a half hour basis at a
fee of $10 per half hour.</li>
	</ul>
</div>
<div class="row">
	<div class="center">
		<%= link_to "Home", root_path, class: "btn btn-success btn-lg nav-btns", style: "margin-right: 20px;" %>
		<%= link_to "Rent This IsoPod", info_path, class: "btn btn-success btn-lg nav-btns" %>
	</div>
</div>

app/views/landings/index.html.erb
<div class="center">
	<%= link_to "Rent This IsoPod", info_path, class: "btn btn-success btn-lg block" %>
	<%= link_to "Learn About IsoPods", about_path, class: "btn btn-success btn-lg block" %>
	<%= link_to "Report An Issue", issue_path, class: "btn btn-success btn-lg block" %>
</div>

app/views/landings/info.html.erb
<div class="row">
	<ul class="info">
		<li class="list">IsoPods are rented on a half hour basis at a
fee of $10 per half hour.</li>
		<li class="list">Upon completion of this setup process you
will be given a code to access the IsoPod</li>
		<li class="list">Your time will then begin, and will not stop
until you end your session on this pad.</li>
		<li class="list">You will have a 5 minute grace period
after every half hour to end your session,
otherwise you will be charged for the next
half hour.</li>
		<li class="list">We ask that you please leave the IsoPod in
the condition you entered it in, and please
make sure to remove all trash and belongings
when you leave.</li>
	</ul>
</div>
<div class="row">
	<div class="center">
		<%= link_to "Home", root_path, class: "btn btn-success btn-lg nav-btns", style: "margin-right: 20px;" %>
		<%= link_to "Next", terms_path, class: "btn btn-success btn-lg nav-btns" %>
	</div>
</div>

app/views/landings/issue.html.erb
<div class="center">
	<h1>Report an Issue</h1>
	<%= form_for 'issue', method:"POST", url: {action: "issue"}, html: {class: "nifty_form"} do |f| %>
		  <%= f.text_field :email, placeholder: "Email", style: "height:50px;width:500px;font-size:2em;text-align:left;"%> <br>
		  <%= f.text_area :message, placeholder: "Message", style: "height:200px;width:500px;font-size:2em;text-align:left;"%> <br>
	    <%= submit_tag "Report", class: "btn btn-success btn-lg nav-btns", style: "margin-top:20px;"%>
	<% end %>
</div>

app/views/landings/ready.html.erb
<div class="row">
	<ul class="info">
		<li class="list">Thank you for completing the set
up process, your IsoPod is ready
for use.</li>
		<li class="list">Once you click the Button below,
your session will start and a code
will be displayed which will allow
you to access the IsoPod.</li>
		<li class="list">When finished, use your 4 digit
pin to unlock this tablet and
hit the END SESSION button to
complete your session.</li>
	</ul>
</div>
<div class="row">
	<div class="center">
		<%= link_to "Home", root_path, class: "btn btn-success btn-lg nav-btns", style: "margin-right: 20px;" %>
		<%= link_to "Next", info_path, class: "btn btn-success btn-lg nav-btns" %>
	</div>
</div>

app/views/landings/rent.html.erb
<h1></h1>

 <div class="payment">
   <div class="card-wrapper"></div>

   <div class="form-container active center">

    <!-- <form action=  "/visits" method="POST" id="payment-form"> -->
      <%= form_tag("/visits", method: "Post") do %>
        <span class="payment-errors"></span>

        <div class="form-row">
          <label class="col-sm-2 col-sm-offset-3 right">
            Card Number
          </label>
          <%= text_field_tag(:number, nil, class: "card-number col-sm-3", size: "20") %>
            <!-- <input type="text" size="20" data-stripe="number" name="number" class="card-number col-sm-3"/> -->
        </div>

        <div class="form-row">
          <label class="col-sm-2 col-sm-offset-3 right">
            Name
          </label>
          <%= text_field_tag(:name, nil, class: "col-sm-3", size: "4") %>
            <!-- <input type="text" size="4" data-stripe="name" name="name"class="col-sm-3"/> -->
        </div>

        <div class="form-row">
          <label class="col-sm-2 col-sm-offset-3 right">
            Exp.Date
          </label>
          <%= text_field_tag(:expiry, nil, class: "card-expiry col-sm-3", placeholder: "MM/YY") %>
            <!-- <input placeholder="MM/YY" type="text" name="expiry" class="col-sm-3 card-expiry"> -->
        </div>

        <div class="form-row">
          <label class="col-sm-2 col-sm-offset-3 right">
            CVC
          </label>
          <%= text_field_tag(:cvc, nil, class: "card-cvc col-sm-3", size: "4") %>
            <!-- <input type="text" size="4" data-stripe="cvc" name="cvc" class="col-sm-3 card-cvc"/> -->
        </div>


        <div class="form-row">
            <label class="col-sm-2 col-sm-offset-3 right">
              Email
            </label>
            <%= email_field(:email,nil, placeholder: "Email", class: "col-sm-3") %>
              <!-- <input placeholder="Email" type="text" class="col-sm-3" name="email"> -->
        </div>

        <div class="form-row">
          <%= submit_tag("Submit Payment", class: "col-sm-6 col-sm-offset-3 btn btn-success btn-lg") %>
          <!-- <button type="submit" class="col-sm-6 col-sm-offset-3 btn btn-success btn-lg">Submit Payment</button> -->
        </div>
      <% end %>
      <!-- </form> -->
   </div>
</div>
<script>
   $('.active form').card({
       container: $('.card-wrapper')
   })
</script>

app/views/landings/terms.html.erb
<div class="row">
	<ul class="info">
<h2>Terms and Conditions</h2>
		<li class="list">IsoPods are rented on a half hour basis at a
fee of $10 per half hour.</li>
		<li class="list">Upon completion of this setup process you
will be given a code to access the IsoPod</li>
		<li class="list">Your time will then begin, and will not stop
until you end your session on this pad.</li>
		<li class="list">You will have a 5 minute grace period
after every half hour to end your session,
otherwise you will be charged for the next
half hour.</li>
		<li class="list">We ask that you please leave the IsoPod in
the condition you entered it in, and please
make sure to remove all trash and belongings
when you leave.</li>
	</ul>
</div>
<div class="row">
	<div class="center">
		<%= link_to "Home", root_path, class: "btn btn-success btn-lg nav-btns", style: "margin-right: 20px;" %>
		<%= link_to "Next", rent_path, class: "btn btn-success btn-lg nav-btns" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IsoPods</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/header" %>
<%= bootstrap_flash %>


<%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield %>

</body>
</html>

app/views/visits/_form.html.erb
<%= form_for @visit, :html => { :class => 'form-horizontal form-model' } do |f| %>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  visits_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/visits/edit.html.erb
<%- model_class = Visit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Visit %></h1>
</div>
<%= render :partial => 'form' %>

app/views/visits/end.html.erb
<div class="row">
	<ul class="info">
		<li class="list">Thank you for Renting an IsoPod,
we hope your session was
enjoyable.</li>
		<li class="list">	Your total time is: <%= @hours %>:<%= @minutes %></li>
		<li class="list">The total charge to your card ammounted to: $<%= @amount %></li>
	</ul>
</div>
<div class="row">
	<div class="center">
		<%= link_to "Finish", root_path, class: "btn btn-success btn-lg nav-btns" %>
	</div>
</div>

app/views/visits/exit.html.erb
<div class="center">
	<h1>Access Your Session</h1>
	<%= form_for 'end', method:"GET", url: {action: "end"}, html: {class: "nifty_form"} do |f| %>
			<%= f.hidden_field :id, :value => params[:id] %>
		  <%= f.text_field :access, placeholder: "Door Code", style: "height:50px;width:200px;font-size:2em;text-align:center;"%> <br>
	    <%= submit_tag "Sign Out", class: "btn btn-success btn-lg nav-btns", style: "margin-top:20px;"%>
	<% end %>
</div>

app/views/visits/index.html.erb
<%- model_class = Visit -%>
<div class="page-header">
  <h1><%=t '.title', :default => Visit %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.id %></td>
        <td><%=l visit.created_at, format: :long %></td>
        <td>
          <%= link_to visit_path(visit), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to visit_path(visit), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_visit_path,
            :class => 'btn btn-primary' %>

app/views/visits/new.html.erb
<%- model_class = Visit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Visit %></h1>
</div>
<%= render :partial => 'form' %>

app/views/visits/show.html.erb
<div class="row">

    <div class="center" style="font-size: 3em;">
      Your pin is:
      <%= @code %>
    </div>
  <ul class="info">
    <li class="list">Your Session has begun, in 15
seconds this screen will go black and
lock.</li>
    <li class="list">To re-access simply tap the screen
and enter your pin.</li>
  </ul>
</div>
<!-- <div class="row">
  <div class="center">
    <%#= link_to "Next", info_path, class: "btn btn-success btn-lg nav-btns" %>
  </div>
</div> -->

<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content" style="margin-top: 300px;">
      <div class="modal-header">
        <h2 class="modal-title">This IsoPod is in use</h2>
      </div>
      <div class="modal-body center">
        <%= link_to "Tap to sign in", exit_path(id: params[:id]), class: "btn btn-danger btn-lg nav-btns" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->